#!/bin/bash

# Simple script to generate HTML from Trivy Operator VulnerabilityReport JSON

cat << 'HTMLTEMPLATE'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trivy Vulnerability Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif; background: #f5f5f5; padding: 20px; }
        .container { max-width: 1400px; margin: 0 auto; background: white; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 8px 8px 0 0; }
        .header h1 { font-size: 28px; margin-bottom: 10px; }
        .header p { opacity: 0.9; font-size: 14px; }
        .summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; padding: 30px; border-bottom: 1px solid #e0e0e0; }
        .summary-card { padding: 20px; border-radius: 8px; text-align: center; }
        .summary-card.critical { background: #ffebee; border-left: 4px solid #d32f2f; }
        .summary-card.high { background: #fff3e0; border-left: 4px solid #f57c00; }
        .summary-card.medium { background: #fff9c4; border-left: 4px solid #fbc02d; }
        .summary-card.low { background: #e3f2fd; border-left: 4px solid #1976d2; }
        .summary-card.unknown { background: #f5f5f5; border-left: 4px solid #757575; }
        .summary-card h3 { font-size: 32px; font-weight: bold; margin-bottom: 5px; }
        .summary-card p { font-size: 14px; color: #666; text-transform: uppercase; }
        .vulnerabilities { padding: 30px; }
        .vuln-section { margin-bottom: 40px; }
        .vuln-section h2 { margin-bottom: 20px; padding-bottom: 10px; border-bottom: 2px solid #e0e0e0; font-size: 20px; }
        .vuln-section.critical h2 { color: #d32f2f; border-color: #d32f2f; }
        .vuln-section.high h2 { color: #f57c00; border-color: #f57c00; }
        .vuln-section.medium h2 { color: #fbc02d; border-color: #fbc02d; }
        .vuln-section.low h2 { color: #1976d2; border-color: #1976d2; }
        .vuln-item { background: #fafafa; border-left: 4px solid #ccc; padding: 20px; margin-bottom: 15px; border-radius: 4px; }
        .vuln-item.critical { border-left-color: #d32f2f; }
        .vuln-item.high { border-left-color: #f57c00; }
        .vuln-item.medium { border-left-color: #fbc02d; }
        .vuln-item.low { border-left-color: #1976d2; }
        .vuln-header { display: flex; justify-content: space-between; align-items: start; margin-bottom: 12px; flex-wrap: wrap; gap: 10px; }
        .vuln-id { font-weight: bold; font-size: 16px; color: #333; }
        .vuln-severity { padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: bold; text-transform: uppercase; }
        .vuln-severity.critical { background: #d32f2f; color: white; }
        .vuln-severity.high { background: #f57c00; color: white; }
        .vuln-severity.medium { background: #fbc02d; color: #333; }
        .vuln-severity.low { background: #1976d2; color: white; }
        .vuln-severity.unknown { background: #757575; color: white; }
        .vuln-title { font-size: 14px; color: #666; margin-bottom: 10px; font-weight: 500; }
        .vuln-details { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 10px; font-size: 13px; margin-top: 12px; }
        .vuln-detail { display: flex; }
        .vuln-detail strong { min-width: 140px; color: #666; }
        .vuln-detail span { color: #333; word-break: break-all; }
        .vuln-links { margin-top: 12px; padding-top: 12px; border-top: 1px solid #e0e0e0; }
        .vuln-links a { color: #1976d2; text-decoration: none; font-size: 13px; margin-right: 15px; }
        .vuln-links a:hover { text-decoration: underline; }
        .no-vulns { text-align: center; padding: 40px; color: #666; font-style: italic; }
        .footer { text-align: center; padding: 20px; color: #666; font-size: 12px; border-top: 1px solid #e0e0e0; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔒 Vulnerability Report</h1>
            <p id="artifact-name">Scanning Results</p>
        </div>
        
        <div class="summary" id="summary">
            <!-- Summary cards will be inserted here -->
        </div>
        
        <div class="vulnerabilities" id="vulnerabilities">
            <!-- Vulnerabilities will be inserted here -->
        </div>
        
        <div class="footer">
            Generated by Trivy Operator | <span id="timestamp"></span>
        </div>
    </div>

    <script>
        const reportData = REPORT_DATA_PLACEHOLDER;
        
        // Set artifact name
        const artifactName = reportData.artifact ? 
            `${reportData.artifact.repository}:${reportData.artifact.tag}` : 
            'Unknown Artifact';
        document.getElementById('artifact-name').textContent = artifactName;
        
        // Set timestamp
        document.getElementById('timestamp').textContent = new Date().toLocaleString();
        
        // Generate summary
        const summary = reportData.summary || {};
        const summaryHtml = `
            <div class="summary-card critical">
                <h3>${summary.criticalCount || 0}</h3>
                <p>Critical</p>
            </div>
            <div class="summary-card high">
                <h3>${summary.highCount || 0}</h3>
                <p>High</p>
            </div>
            <div class="summary-card medium">
                <h3>${summary.mediumCount || 0}</h3>
                <p>Medium</p>
            </div>
            <div class="summary-card low">
                <h3>${summary.lowCount || 0}</h3>
                <p>Low</p>
            </div>
            <div class="summary-card unknown">
                <h3>${summary.unknownCount || 0}</h3>
                <p>Unknown</p>
            </div>
        `;
        document.getElementById('summary').innerHTML = summaryHtml;
        
        // Group vulnerabilities by severity
        const vulnerabilities = reportData.vulnerabilities || [];
        const grouped = {
            CRITICAL: [],
            HIGH: [],
            MEDIUM: [],
            LOW: [],
            UNKNOWN: []
        };
        
        vulnerabilities.forEach(vuln => {
            const severity = (vuln.severity || 'UNKNOWN').toUpperCase();
            if (grouped[severity]) {
                grouped[severity].push(vuln);
            } else {
                grouped.UNKNOWN.push(vuln);
            }
        });
        
        // Generate vulnerability sections
        let vulnHtml = '';
        ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'UNKNOWN'].forEach(severity => {
            const vulns = grouped[severity];
            if (vulns.length > 0) {
                const severityLower = severity.toLowerCase();
                vulnHtml += `<div class="vuln-section ${severityLower}">`;
                vulnHtml += `<h2>${severity} (${vulns.length})</h2>`;
                
                vulns.forEach(vuln => {
                    vulnHtml += `
                        <div class="vuln-item ${severityLower}">
                            <div class="vuln-header">
                                <div class="vuln-id">${vuln.vulnerabilityID || 'N/A'}</div>
                                <span class="vuln-severity ${severityLower}">${severity}</span>
                            </div>
                            ${vuln.title ? `<div class="vuln-title">${vuln.title}</div>` : ''}
                            <div class="vuln-details">
                                <div class="vuln-detail">
                                    <strong>Package:</strong>
                                    <span>${vuln.resource || 'N/A'}</span>
                                </div>
                                <div class="vuln-detail">
                                    <strong>Installed Version:</strong>
                                    <span>${vuln.installedVersion || 'N/A'}</span>
                                </div>
                                <div class="vuln-detail">
                                    <strong>Fixed Version:</strong>
                                    <span>${vuln.fixedVersion || 'Not Fixed'}</span>
                                </div>
                                ${vuln.score !== undefined ? `
                                <div class="vuln-detail">
                                    <strong>Score:</strong>
                                    <span>${vuln.score}</span>
                                </div>
                                ` : ''}
                            </div>
                            ${vuln.primaryLink || (vuln.links && vuln.links.length > 0) ? `
                            <div class="vuln-links">
                                ${vuln.primaryLink ? `<a href="${vuln.primaryLink}" target="_blank">📋 Primary Reference</a>` : ''}
                                ${vuln.links ? vuln.links.slice(0, 3).map(link => `<a href="${link}" target="_blank">🔗 Reference</a>`).join('') : ''}
                            </div>
                            ` : ''}
                        </div>
                    `;
                });
                
                vulnHtml += '</div>';
            }
        });
        
        if (!vulnHtml) {
            vulnHtml = '<div class="no-vulns">🎉 No vulnerabilities found!</div>';
        }
        
        document.getElementById('vulnerabilities').innerHTML = vulnHtml;
    </script>
</body>
</html>
HTMLTEMPLATE
